### ISSUE TITLE
Recognized as Scorm 1.2 in LMS

### ISSUE THREAD

**Issue by guppyplopp** [pipwerks/scorm-api-wrapper#30]
Cornerstone LMS recognizes it as Scorm 1.2 though it is set to act as 2004. Not sure if this is just a visual thing, but the customers get nervous... 
![image003](https://cloud.githubusercontent.com/assets/20163876/25892249/11a1f650-3574-11e7-8bcf-c77409c7f03f.png)

**Comment by moloko** [comment]
hi @guppyplopp - it's the `<schemaversion>` setting in imsmanifest.xml that tells the LMS what version of SCORM the SCO wants to use... 

The setting in the API wrapper is there because some LMSes (Saba, for example) always make both versions of the API available to the SCO. So in those cases the API wrapper needs to be told which to use; it will default to the SCORM 2004 API if not told to do otherwise.

**Comment by pipwerks** [comment]
The manifest file needs to be swapped for a proper SCORM 2004 manifest. Some of my older example files had crappy manifests. The manifests are not hosted on GitHub, can you tell me which one you downloaded and where you found it?

**Comment by guppyplopp** [comment]
The manifest is from your scorm-test file "SCORM_wrapper_test_SCORM12". 
I just changed the settings and some names to 2004.

**Comment by pipwerks** [comment]
OK, that explains it. SCORM 2004 and SCORM 1.2 require different manifests and supporting schema files, you can't just change a couple of fields. Grab a proper SCORM 2004 manifest. https://github.com/pipwerks/SCORM-Manifests
