### ISSUE TITLE
NPM module

### ISSUE THREAD

**Issue by NemoStein** [pipwerks/scorm-api-wrapper#33]
Is there any real explanation why this project isn't published in NPM repo?
It seems like it's ready for it, based on the current package.json.

ps: to be able to publish this the name field must be changed, as the [scorm-api-wrapper](https://www.npmjs.com/package/scorm-api-wrapper) is already taken by some module which depends on another module ([pipwerks-scorm-api-wrapper](https://www.npmjs.com/package/pipwerks-scorm-api-wrapper)) which in turn is a module wrapper for this project... What a mess... ^^"

**Comment by pipwerks** [comment]
This codebase predates the existence of NPM. It has not been significantly updated since before NodeJS existed. It was not written in a modern modular fashion because that's now how people packaged JS libraries a decade ago. It's certainly possible to refactor it into a modular pattern and publish on NPM/CDN/what-have-you, which [someone has already done](https://www.npmjs.com/package/pipwerks-scorm-api-wrapper).

The [other link you point to](https://www.npmjs.com/package/scorm-api-wrapper) is an unrelated library. It has nothing to do with the pipwerks SCORM wrapper.

**Comment by NemoStein** [comment]
You're completely right... I've messed up my links!
Of course this project is way older than NPM itself, but the last commit was a year ago, which is "recent enough", so i thought it could be published simply by exporting the `pipwerks` object.

But, again, you're completely right. The current codebase may be unfit for publication as is.

**Comment by pipwerks** [comment]
Closing since there is already a version available on NPM
