### ISSUE TITLE
Chrome 80

### ISSUE THREAD

**Issue by rick-perkins** [pipwerks/scorm-api-wrapper#45]
With the release of Chrome 80 there is an issue with sending data when the unload is triggered.
I was wondering if there was going to be an update or if not, any advise on how to solve this would be great?
I am still very new to all this.
Thanks Rick

**Comment by moloko** [comment]
@rick-perkins the issue really lies on the LMS side, it will be using a synchronous XMLHttpRequest to save the data when `LMSFinish` is called by the course. Chrome now blocks this from being run 'on page dismissal'. 

The suggested workaround is to use `sendBeacon` instead - but this would have to be done by your LMS provider. Have you contacted them to see if there's an update available? This change was flagged some time ago by Chrome so hopefully they should have sorted something already.

Otherwise, all you can really do is add a exit button to your course and have that trigger your course exit routine instead. The problem is, of course, that not all users will use this and just close the window anyway. You could also trigger an 'are you sure you want to leave' browser prompt on window close in the event that the learner hasn't clicked the course exit button...

**Comment by rick-perkins** [comment]
@moloko, Thank you for your reply and help in this matter.
I have spoken to the LMS supplier and they have just said there is not much they can do from their end and its the scorm code I need to change, they also added a comment about adding the exit button as well. 
We can force the exit button very easy in this LMS platform. The scorm data is very limited because all I am doing is just keeping a track of the last page viewed and if its been completed, may be due to this I could just stop triggering the unload part.

The issue I am seeing is when the exit button is used in the LMS to close the course, the popup window just freezes and never closes. Just can not work out why this would happen because I don't control the popup window.

**Comment by moloko** [comment]
> I have spoken to the LMS supplier and they have just said there is not much they can do from their end and its the scorm code I need to change

😮  what professionalism! I can assure you that there absolutely is something they can do and that they are simply trying to fob you off. Please feel free to name and shame them!

(For reference, [here is a post from the folks at SCORM Cloud](https://support.scorm.com/hc/en-us/articles/360035814314-Blocked-SCORM-Exit-Postbacks-with-Google-Chrome-80-and-Above) explaining that they can fix this on the LMS side - and [here's the Moodle issue reference](https://tracker.moodle.org/browse/MDL-67175) that documents it being fixed by them (in Moodle v3.6.9))

I guess you need to find out whether they mean add the exit button from the LMS platform or add one into the course. I was referring to adding one into the course itself.

Either way, none of this is really a pipwerks SCORM wrapper issue so we should probably stop having this conversation here. There's a google group [here](https://groups.google.com/forum/#!forum/elearning-technology-and-development) that would be more appropriate for discussions like this.

**Comment by rick-perkins** [comment]
Thank you very much and confirming what I was thinking anyway.

**Comment by pipwerks** [comment]
Hi @rick-perkins. 

@moloko is on the money (thanks, Matt). Nothing you can do about it -- the xmlhttprequest code is all owned/managed by the server. All you can do is modify your use cases to avoid using the beforeunload and unload events in your course. I replied to your post in the E-Learning Tech and Dev Google Group echoing this conversation but without @moloko's
 excellent links. I will reply with a link to this issue so others can read @moloko's comments.

- philip
